[run]
build = "npm run build"

[gptengineer-app]
project_id = "577422e1-f613-427c-9c9b-3ec32af994f5"

[[gptengineer-app.openapi]]
url = "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/color.pizza/1.0.0/openapi.yaml"
